# Force OS X.
language: objective-c

matrix:
  include:
    - env: OSX=10.12
      os: osx
      osx_image: xcode8.2
      rvm: system
    - env: OSX=10.11
      os: osx
      osx_image: xcode8
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
    - brew update
    - brew tap drolando/deadsnakes

install:
    # Make sure python is installed
    - brew list python || brew install python
    - brew install python26
    # Make sure python3 is installed
    - brew list python3 || brew install python3
    - brew install python31
    - brew install python32
    - brew install python33
    - brew install python34

script:
    - brew test python26
    - brew test python31
    - brew test python32
    - brew test python33
    - brew test python34
